export enum AgentCapability {
  READ_ACCOUNTS = 'READ_ACCOUNTS',
  READ_TRANSACTIONS = 'READ_TRANSACTIONS',
  READ_FINANCIAL_SUMMARY = 'READ_FINANCIAL_SUMMARY',
  READ_BUDGETS = 'READ_BUDGETS',
  CREATE_TRANSACTION = 'CREATE_TRANSACTION',
  UPDATE_TRANSACTION = 'UPDATE_TRANSACTION',
  DELETE_TRANSACTION = 'DELETE_TRANSACTION',
  CREATE_TRANSFER = 'CREATE_TRANSFER',
  MANAGE_MEMORY = 'MANAGE_MEMORY',
}
